import type {
  CurrentLanguage,
  SocialLink,
  TimelineEntry,
} from "@/components/about/types";

export const SOCIAL_LINKS: SocialLink[] = [
  {
    alt: "My github.io",
    href: "https://github.com/Will-D-Wang",
    src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/github/github-original.svg",
  },
  {
    alt: "Will-Dingan-Wang",
    href: "https://linkedin.com/in/will-d-wang",
    src: "https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/linkedin.svg",
  },
];

export const CURRENT_LANGUAGES: CurrentLanguage[] = [
  { label: "Python", href: "https://www.python.org/" },
  { label: "Golang", href: "https://golang.org/" },
  {
    label: "JavaScript",
    href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  },
  {
    label: "Jenkins CI/CD",
    href: "https://www.jenkins.io/doc/book/pipeline/",
  },
  {
    label: "Teamcity",
    href: "https://www.jetbrains.com/help/teamcity/teamcity-documentation.html",
  },
  { label: "Terraform", href: "https://www.terraform.io/" },
  { label: "Kubernetes", href: "https://kubernetes.io/" },
  { label: "Docker", href: "https://www.docker.com/" },
];

export const CURRENT_STATUS: string[] = [
  "🎵️🎶️ I'm playing with backend, micro-service, system design, DevOps, SRE, Teamcity, AI.",
  "🌱🌳️ I'm learning history, psychology, philosophy, management.",
  "🍻️🥂️ I'm looking to collaborate on more interesting open source projects.",
  "💬🗒️ Ask me about test automation, philosophy, python, AI.",
  "☯️❤️ Fun fact: Life is the most precious journey, only once in the universe, enjoy it everyday.",
];

export const TIMELINE_ENTRIES: TimelineEntry[] = [
  {
    type: "experience",
    title: "Platform Engineer",
    periods: [
      {
        organization: "HP",
        role: "Software Applications Engineer 3",
        location: "Vancouver, B.C., Canada · Hybrid",
        startTime: "2024-01",
        endTime: "present",
        icons: [
          "Python",
          "TypeScript",
          "AWS",
          "Kubernetes",
          "Node.js",
          "Terraform",
        ],
        stackLine:
          "Python, TypeScript, Node.js, Kubernetes, Terraform, AWS",
        details: [
          "Led the Pipeline group to build CI/CD pipelines for the Anyware Manager product line across SaaS and on-prem releases, while contributing backend improvements for safer and faster releases.",
          "Led system test development on AWS to validate the on-prem solution end-to-end, including backend API and service validation plus integration coverage.",
          "Owned TeamCity CI/CD infrastructure, creating reusable meta-runners, build templates, and hundreds of build configurations to support backend delivery at scale.",
          "Implemented and validated security compliance features across AWS and Azure environments.",
          "Joined the Platform team to drive DevOps and SRE objectives, improving backend service reliability, release stability, and operational readiness.",
          "Owned security reviews and security feature delivery, and contributed to SOC 2 readiness and audit support.",
          "Worked across DevOps, Platform, and SRE responsibilities to support backend development, CI/CD reliability, infrastructure, and production operations.",
        ],
      },
    ],
  },
  {
    type: "experience",
    title: "DevOps Engineer",
    periods: [
      {
        organization: "HP",
        role: "Software Applications Engineer 3",
        location: "Vancouver, B.C., Canada · Hybrid",
        startTime: "2021-10",
        endTime: "2023-12",
        icons: [
          "Python",
          "Terraform",
          "Kubernetes",
          "Golang",
          "AWS",
          "TeamCity",
        ],
        stackLine:
          "Python, Terraform, Kubernetes, AWS, TeamCity, Golang",
        details: [
          "Led the Pipeline group to build CI/CD pipelines for the Anyware Manager product line across SaaS and on-prem releases, while contributing backend improvements for safer and faster releases.",
          "Reduced on-prem SaaS release time from multiple days to about 2 hours by streamlining CI/CD pipelines, backend build and test workflows, and system-test automation.",
          "Owned TeamCity CI/CD infrastructure and supported backend delivery at scale.",
        ],
      },
      {
        organization: "Teradici, an HP Company",
        role: "Software Developer - Staff",
        location: "Greater Vancouver, B.C., Canada",
        startTime: "2021-01",
        endTime: "2021-10",
        icons: [
          "Python",
          "Terraform",
          "Kubernetes",
          "AWS",
          "Golang",
          "Docker",
        ],
        stackLine: "Golang, Python, Terraform, Kubernetes, Docker, AWS",
        details: [
          "Worked on a microservice-based SaaS platform deployed on Kubernetes and Docker.",
          "Contributed to the SaaS on-premise application in Go, improving deployment reliability and usability.",
          "Developed and maintained Python test automation scripts to strengthen regression coverage.",
          "Managed Google Cloud Platform and AWS resources using Terraform.",
          "Served as CI/CD and release gatekeeper, reviewing pipeline health, enforcing quality checks, and coordinating release readiness.",
        ],
      },
    ],
  },
  {
    type: "education",
    title: "Master of Science - Computer Science",
    periods: [
      {
        organization: "Georgia Institute of Technology",
        role: "Master of Science - Computer Science (Grade: 3.82/4.0)",
        location: "Atlanta, GA, USA",
        startTime: "2021-01",
        endTime: "2024-12",
        icons: [
          "C",
          "Python",
          "Docker",
          "Linux",
          "Apache Spark",
          "Pandas",
          "PyTorch",
          "Git",
          "GCP",
          "D3.js",
          "LaTeX",
          "MongoDB",
          "NumPy",
          "Scikit-learn",
        ],
        tech_stacks: [
          "CSE6242 - Data and Visual Analytics",
          "CS 7646 - Machine Learning for Trading",
          "CS 6310 - Software Architecture and Design",
          "CS 6300 - Software Development Process",
          "CS 6515 - Introduction to Graduate Algorithms",
          "CS 6601 - Artificial Intelligence",
          "CS 7643 - Deep Learning",
          "CS 6035 - Introduction to Information Security",
          "CS 6210 - Advanced Operating Systems",
          "CS 6211 - System Design for Cloud Computing",
          "CS 7650 - Natural Language Processing",
        ],
      },
    ],
  },
  {
    type: "experience",
    title: "SDET (Software Development Engineer in Test)",
    periods: [
      {
        organization: "Sierra Wireless",
        role: "Senior Validation Engineer",
        location: "Richmond, British Columbia, Canada",
        startTime: "2019-10",
        endTime: "2021-01",
        icons: [
          "Python",
          "Docker",
          "Jenkins",
          "Groovy",
          "Elasticsearch",
          "Kibana",
        ],
        stackLine:
          "Python, Jenkins, Groovy, Docker, Elasticsearch, Kibana",
        details: [
          "Worked on the Legato Delivery team within the IoT Business Unit.",
          "Maintained the Legato Testing Project, a pytest-based framework with Pexpect-driven CLI validation.",
          "Developed and maintained Jenkins pipeline Groovy scripts and Docker images to automate CI/CD workflows.",
          "Introduced test-driven development practices for Jenkins pipeline Groovy scripts to improve reliability and reduce regressions.",
          "Automated performance testing and published results to Kibana dashboards.",
          "Automated Python test reporting by collecting metrics from Jira and Quality Center via REST APIs, then generating Confluence pages.",
          "Served as Scrum Master for the delivery team, facilitating sprint ceremonies and removing blockers.",
        ],
      },
      {
        organization: "Intel Corporation (Contractor)",
        role: "Validation Engineer",
        location: "Vancouver, B.C., Canada",
        startTime: "2018-02",
        endTime: "2019-09",
        icons: ["Python", "VS-Code", "Git", "TeamCity", "JIRA", "Confluence"],
        stackLine: "Python, TeamCity, Git, VS Code, Jira, Confluence",
        details: [
          "Designed and implemented system tests and automation tools in Python for the Intel NSG SSD Firmware Platform Service team.",
          "Built a tool to collect QuickBuild results via REST APIs and analyze outcomes to improve CI visibility.",
          "Maintained and improved TeamCity configurations to support reliable builds and test execution.",
          "Developed and enabled system tests in the CI pipeline, increasing automation coverage for platform services.",
          "Introduced unit and integration tests for internal test tools using unittest and pytest, applying TDD to improve maintainability.",
        ],
      },
    ],
  },
  {
    type: "experience",
    title: "Software Engineer",
    periods: [
      {
        organization: "Intel Corporation (Contractor)",
        role: "Software Engineer",
        location: "Vancouver, B.C., Canada",
        startTime: "2017-04",
        endTime: "2018-01",
        icons: ["C", "Python", "Git", "TeamCity", "JIRA", "Confluence"],
        stackLine: "C, Python, TeamCity, Git, Jira, Confluence",
        details: [
          "Programmed and debugged SSD firmware in C for the Intel SSD Firmware Product team.",
          "Maintained firmware for a production series of Intel NAND SSD drives, supporting feature updates and defect fixes.",
          "Regularly reported and analyzed firmware system regression and CI test results, working across teams to drive issue resolution.",
        ],
      },
      {
        organization: "HCL Technologies",
        role: "Software Developer",
        location: "Burnaby, B.C., Canada",
        startTime: "2016-01",
        endTime: "2017-03",
        icons: ["C", "Python", "Linux", "Git", "Bash", "CMake"],
        stackLine: "C, Python, Linux, Git, Bash, CMake",
        details: [
          "Worked as a contractor supporting Ericsson projects following the acquisition.",
          "Developed and maintained hardware simulation software to support SSR feature development.",
          "Implemented and tested Layer 2 ACL functionality with automated and manual test cases.",
        ],
      },
      {
        organization: "Ericsson",
        role: "Software Developer",
        location: "Burnaby, B.C., Canada",
        startTime: "2014-05",
        endTime: "2015-12",
        icons: ["C", "Python", "Linux", "Git", "Bash", "CMake"],
        stackLine: "C, Python, Linux, Git, Bash, CMake",
        details: [
          "Joined the Forwarding Service team for the Smart Service Router.",
          "Developed ACL features in IP-OS and collaborated on Service Sync and Software Quality Ranking initiatives.",
          "Built a Python unit test framework for ACL and improved coverage and regression safety.",
          "Designed module APIs and wrote Doxygen documentation for maintainable interfaces.",
          "Led performance testing and optimization of a pub-sub system supporting 128K circuits.",
          "Drove profiling and coverage reporting to improve runtime efficiency and code quality.",
        ],
      },
    ],
  },
  {
    type: "education",
    title: "Bachelor of Applied Science (BASc) - Computer Science",
    periods: [
      {
        organization: "Simon Fraser University",
        role: "BASc - Computer Science (Concentration on operating systems and networking)",
        location: "Burnaby, B.C., Canada",
        startTime: "2011-01",
        endTime: "2014-12",
        icons: ["C", "C++", "Java", "Python", "JavaScript", "Linux", "MySQL"],
        tech_stacks: [
          "CMPT-225 - Data Structure/Programming",
          "CMPT-275 - Software Engineering",
          "CMPT-300 - Operating System",
          "CMPT-307 - Data Structure",
          "CMPT-354 - Multimedia Systems",
          "CMPT-371 - Data Communication/Networking",
          "CMPT-419 - Machine Learning",
          "CMPT-431 - Distributed Systems",
          "CMPT-470 - Web-based Information Systems",
          "CMPT-477 - Introduction to Formal Verification",
          "CMPT-741 - Data Mining",
          "CMPT-705 - Design/Analysis Algorithms",
          "CMPT-771 - Internet Architecture and Protocols",
        ],
        details: [
          "Tutored CMPT 130 lab sessions and guided students in debugging and improving C programs.",
          "Graded programming assignments and exams, providing clear and actionable feedback.",
        ],
      },
    ],
  },
];
